const arr=[1,3,5,7];
console.log(arr);
arr.push(9);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(0);
console.log(arr);
arr.shift();
console.log(arr);
s=arr.join("");
console.log(s);
n=s.split("");
console.log(n);